
# Uncomment the next line to define a global platform for your project
#source 'https://git.coding.net/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
target 'ocRouter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

pod 'MGJRouter', '~>0.9.0'
pod 'Masonry', '~>1.1.0'

end
